# Development Configuration Example
# Lightweight configuration for development environment

database:
  type: MYSQL
  host: localhost
  port: 3306
  name: dev_db
  username: dev_user
  password: dev_password

backup:
  local:
    enabled: true
    path: ./dev-backups
    retention: 7           # Keep only 7 days for development
    compress: false        # Skip compression for faster development
    enableChecksum: false  # Skip checksum for faster development
    checksumAlgorithm: MD5

  # Disable S3 and email for development
  s3:
    enabled: false
    
  email:
    enabled: false

# Manual backup only (no scheduling)
schedule:
  enabled: false