name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Run tests
      run: ./gradlew test
      
    - name: Build project
      run: ./gradlew build
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ github.ref_name }}
        body: |
          ## Changes in this Release
          
          This release is automatically built and published to JitPack.
          
          ### Usage
          ```gradle
          repositories {
              mavenCentral()
              maven { url 'https://jitpack.io' }
          }
          
          dependencies {
              implementation 'com.github.ckr3453:db-backup4j:${{ github.ref_name }}'
          }
          ```
          
          Visit [JitPack](https://jitpack.io/#ckr3453/db-backup4j) for more information.
        draft: false
        prerelease: false